name: saga_monitor
maintainer: Bilal Uslu (@bilaluslu)
description: Simple Saga Monitor for monitoring sagas and effects created by Redux Saga.
homepage: https://github.com/reduxsaga/saga_monitor
version: 2.0.1
repository: https://github.com/reduxsaga/saga_monitor

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  redux: ^5.0.0
  redux_saga: ^3.0.2

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
