name: saga_monitor
maintainer: Bilal Uslu (@bilaluslu)
description: Simple Saga Monitor for monitoring sagas and effects created by Redux Saga.
homepage: https://github.com/reduxsaga/saga_monitor
version: 1.1.0
repository: https://github.com/reduxsaga/saga_monitor

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  redux: ^5.0.0
  redux_saga: ^2.1.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.7
