name: saga_monitor
maintainer: Bilal Uslu (@bilaluslu)
description: Simple Saga Monitor for monitoring sagas and effects created by Redux Saga.
homepage: https://github.com/reduxsaga/saga_monitor
version: 1.0.2
repository: https://github.com/reduxsaga/saga_monitor

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  redux: ^4.0.0
  redux_saga: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
